/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Community Working Group",
  "tagline": "Facilitate broad adoption of Green Software standards and best practices through the creation of partnerships, content, events and programs",
  "url": "https://community-wg.greensoftware.foundation/",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "Green-Software-Foundation",
  "projectName": "community_wg",
  "deploymentBranch": "web",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/Users/osamajandali/Desktop/Others/Greensoftware/Dev/community_wg/sidebars.js",
          "routeBasePath": "/",
          "editUrl": "https://github.com/Green-Software-Foundation/community_wg/"
        },
        "blog": false,
        "theme": {
          "customCss": "/Users/osamajandali/Desktop/Others/Greensoftware/Dev/community_wg/src/css/custom.css"
        },
        "gtag": {
          "trackingID": "G-593HJXNS18"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5,
          "ignorePatterns": [
            "/tags/**"
          ],
          "filename": "sitemap.xml"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "Community Working Group",
      "logo": {
        "alt": "Green Software TODO Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "href": "https://greensoftware.foundation/",
          "position": "right",
          "label": "a Green Software Foundation project"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Links",
          "items": [
            {
              "label": "Github",
              "href": "https://github.com/Green-Software-Foundation/community_wg"
            },
            {
              "label": "Website",
              "href": "https://community-wg.greensoftware.foundation"
            }
          ]
        },
        {
          "title": "LEGAL",
          "items": [
            {
              "label": "Trademark Policy",
              "href": "https://greensoftware.foundation/policy/trademark"
            },
            {
              "label": "Terms and Privacy Policy",
              "href": "https://greensoftware.foundation/policy/terms"
            }
          ]
        },
        {
          "title": "GSF Info",
          "items": [
            {
              "label": "Green Software Foundation",
              "href": "https://greensoftware.foundation"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/gsfcommunity"
            },
            {
              "label": "Linkedin",
              "href": "https://www.linkedin.com/company/green-software-foundation/"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2022 Joint Development Foundation Projects, LLC, Green Software Foundation Series"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "disableSwitch": true,
      "defaultMode": "light",
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "plugins": [
    [
      "@docusaurus/plugin-ideal-image",
      {
        "quality": 90,
        "max": 1030,
        "min": 640,
        "steps": 2,
        "disableInDev": false
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
